micronaut:
  application:
    name: graphql-mn

graphql:
  enable: true
  path: graphql
  graphiql:
    enabled: true
    version: 0.13.2
    path: /graphiql
    template-path: classpath:graphiql/index.html
    template-parameters:
    page-title: DemoGraphiQL